baseurl: ''
canonicalurl: 'https://sentimony.com'
include: ['_pages']
exclude: [
    'README.md',
    'package.json',
    'package-lock.json',
    'node_modules/',
    'gulpfile.js',
    'Gemfile',
    'Gemfile.lock',
    'yarn.lock'
  ]
includes_dir: ./_components
data_dir: ./_components

future: true

slogan: Psychedelic Music Label
