baseurl: ''
include: ['_pages']
exclude: ['README.md', 'package.json', 'node_modules/', 'gulpfile.js', 'Gemfile', 'Gemfile.lock', 'yarn.lock']
includes_dir: ./_components
data_dir: ./_components

slogan: Psychedelic Music Label
